## Table of contents
* [Introduction: Business Problem](#introduction)
* [Data](#data)
* [Methodology](#methodology)
* [Analysis](#analysis)
* [Results and Discussion](#results)
* [Conclusion](#conclusion)

A young entrepreneur who made handmade jewelries and sandals in Haiti, the name of her company is LOV’ART. In Haiti it’s easy to sell product and the customers love them, often she found people who live in others countries who want to buy LOVE’ART’s products sometimes it is very difficult to find the opportunity to sell the product in the international market, she would like to analyze some states in some countries to find a better place to open a LOV’ART store so she can sell the products easily and also enhance Haitian production at the international level.

# Introduction: Business Problem
In this project we will try to find an optimal location to open a store who made handmade jewelries and sandals in USA or Canada. Specifically, this report will be targeted other entrepreneur who would like to expand their business in the international market can be interest.

# DATA
number of existing jewelleries in the neighborhood (any type of jewelleries)

In [9]:
#import the libraries 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt # plotting
import os # accessing directory structure

In [10]:
# read the file and assign it to the variable "df_toronto"
df_toronto = pd.read_csv('MCI_2014_to_2019 (1).csv')
df_toronto.head()

,X,Y,Index_,event_unique_id,occurrencedate,reporteddate,premisetype,ucr_code,ucr_ext,offence,...,occurrencedayofyear,occurrencedayofweek,occurrencehour,MCI,Division,Hood_ID,Neighbourhood,Long,Lat,ObjectId
0,-8.816401e+06,5.434587e+06,701,GO-20141756319,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,1430,100,Assault,...,83.0,Monday,1,Assault,D42,132,Malvern (132),-79.199081,43.800281,1
1,-8.837252e+06,5.413357e+06,901,GO-20143006885,2014/09/27 00:00:00+00,2014/09/29 00:00:00+00,Other,2120,200,B&E,...,270.0,Saturday,16,Break and Enter,D52,76,Bay Street Corridor (76),-79.386383,43.662472,2
2,-8.862433e+06,5.422276e+06,702,GO-20141756802,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,2120,200,B&E,...,83.0,Monday,6,Break and Enter,D23,1,West Humber-Clairville (1),-79.612595,43.720406,3
3,-8.833104e+06,5.431887e+06,703,GO-20141760570,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Apartment,2120,200,B&E,...,83.0,Monday,15,Break and Enter,D33,47,Don Valley Village (47),-79.349121,43.782772,4
4,-8.845311e+06,5.413667e+06,902,GO-20142004859,2014/05/03 00:00:00+00,2014/05/03 00:00:00+00,Commercial,1610,210,Robbery - Business,...,123.0,Saturday,2,Robbery,D11,90,Junction Area (90),-79.458778,43.664490,5

In [11]:
df_houses = pd.read_csv('houses.csv') 
df_houses.head()

,index,title,final_price,list_price,bedrooms,bathrooms,sqft,parking,description,mls,type,full_link,full_address,lat,long,city_district,mean_district_income,district_code
0,0,"1303 - 38 Grenville St, Toronto (C4461599) | Z...",855000,870000,2 + 1 beds,2 baths,800–899 sq. ft.,1 parking,"Luxurious And Spacious Murano Tower. 2+1, 2 Ba...",C4461599,Condo Apt,https://www.zoocasa.com/toronto-on-real-estate...,"38 Grenville St, Toronto , Ontario, Canada",43.661896,-79.385748,Bay Street Corridor,56526,76
1,1,"2 Cabot Crt, Toronto (W4502992) | Zoocasa",885000,898000,3 beds,2 baths,N/A sq. ft.,6 parking,Fantastic Opportunity To Live Within The Histo...,W4502992,Semi-Detached,https://www.zoocasa.com/toronto-on-real-estate...,"2 Cabot Crt, Toronto , Ontario, Canada",43.646982,-79.530356,Islington-City Centre West,52787,14
2,2,"1504 - 30 Roehampton Ave, Toronto (C4511330) |...",550000,549900,1 beds,1 baths,500–599 sq. ft.,no parking,Bright Sunfilled Spacious 1 Bdr Unit; Floor To...,C4511330,Condo Apt,https://www.zoocasa.com/toronto-on-real-estate...,"30 Roehampton Ave, Toronto , Ontario, Canada",43.708472,-79.397498,Mount Pleasant West,57039,104
3,3,"514 - 65 East Liberty St, Toronto (C4515763) |...",665000,600000,1 + 1 beds,1 baths,600–699 sq. ft.,1 parking,Rare Loft-Like Condo In Liberty Village W/ 18'...,C4515763,Condo Apt,https://www.zoocasa.com/toronto-on-real-estate...,"65 East Liberty St, Toronto , Ontario, Canada",43.638399,-79.414448,Niagara,70623,82
4,4,"61 Twelfth St, Toronto (W4519375) | Zoocasa",825513,839000,2 beds,2 baths,N/A sq. ft.,1 parking,Location! Location! Location. Your Cottage In ...,W4519375,Detached,https://www.zoocasa.com/toronto-on-real-estate...,"61 Twelfth St, Toronto , Ontario, Canada",43.597096,-79.509612,New Toronto,44101,18

In [13]:
df_toronto.head()

,X,Y,Index_,event_unique_id,occurrencedate,reporteddate,premisetype,ucr_code,ucr_ext,offence,...,occurrencedayofyear,occurrencedayofweek,occurrencehour,MCI,Division,Hood_ID,Neighbourhood,Long,Lat,ObjectId
0,-8.816401e+06,5.434587e+06,701,GO-20141756319,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,1430,100,Assault,...,83.0,Monday,1,Assault,D42,132,Malvern (132),-79.199081,43.800281,1
1,-8.837252e+06,5.413357e+06,901,GO-20143006885,2014/09/27 00:00:00+00,2014/09/29 00:00:00+00,Other,2120,200,B&E,...,270.0,Saturday,16,Break and Enter,D52,76,Bay Street Corridor (76),-79.386383,43.662472,2
2,-8.862433e+06,5.422276e+06,702,GO-20141756802,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,2120,200,B&E,...,83.0,Monday,6,Break and Enter,D23,1,West Humber-Clairville (1),-79.612595,43.720406,3
3,-8.833104e+06,5.431887e+06,703,GO-20141760570,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Apartment,2120,200,B&E,...,83.0,Monday,15,Break and Enter,D33,47,Don Valley Village (47),-79.349121,43.782772,4
4,-8.845311e+06,5.413667e+06,902,GO-20142004859,2014/05/03 00:00:00+00,2014/05/03 00:00:00+00,Commercial,1610,210,Robbery - Business,...,123.0,Saturday,2,Robbery,D11,90,Junction Area (90),-79.458778,43.664490,5

In [14]:
df_toronto.rename(columns = {'offence':'type of crime'}, inplace = True)

In [15]:
#type of each variables 
df_toronto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206435 entries, 0 to 206434
Data columns (total 29 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   X                    206435 non-null  float64
 1   Y                    206435 non-null  float64
 2   Index_               206435 non-null  int64
 3   event_unique_id      206435 non-null  object
 4   occurrencedate       206435 non-null  object
 5   reporteddate         206435 non-null  object
 6   premisetype          206435 non-null  object
 7   ucr_code             206435 non-null  int64
 8   ucr_ext              206435 non-null  int64
 9   type of crime        206435 non-null  object
 10  reportedyear         206435 non-null  int64
 11  reportedmonth        206435 non-null  object
 12  reportedday          206435 non-null  int64
 13  reporteddayofyear    206435 non-null  int64
 14  reporteddayofweek    206435 non-null  object
 15  reportedhour         206435 non-null  int64
 16  occurrenceyear       206376 non-null  float64
 17  occurrencemonth      206376 non-null  object
 18  occurrenceday        206376 non-null  float64
 19  occurrencedayofyear  206376 non-null  float64
 20  occurrencedayofweek  206376 non-null  object
 21  occurrencehour       206435 non-null  int64
 22  MCI                  206435 non-null  object
 23  Division             206435 non-null  object
 24  Hood_ID              206435 non-null  int64
 25  Neighbourhood        206435 non-null  object
 26  Long                 206435 non-null  float64
 27  Lat                  206435 non-null  float64
 28  ObjectId             206435 non-null  int64
dtypes: float64(7), int64(10), object(12)
memory usage: 45.7+ MB

In [16]:
df_toronto.shape

(206435, 29)

In [17]:
df_toronto.isnull().sum(axis=0)

X                       0
Y                       0
Index_                  0
event_unique_id         0
occurrencedate          0
reporteddate            0
premisetype             0
ucr_code                0
ucr_ext                 0
type of crime           0
reportedyear            0
reportedmonth           0
reportedday             0
reporteddayofyear       0
reporteddayofweek       0
reportedhour            0
occurrenceyear         59
occurrencemonth        59
occurrenceday          59
occurrencedayofyear    59
occurrencedayofweek    59
occurrencehour          0
MCI                     0
Division                0
Hood_ID                 0
Neighbourhood           0
Long                    0
Lat                     0
ObjectId                0
dtype: int64

In [18]:
df_toronto

,X,Y,Index_,event_unique_id,occurrencedate,reporteddate,premisetype,ucr_code,ucr_ext,type of crime,...,occurrencedayofyear,occurrencedayofweek,occurrencehour,MCI,Division,Hood_ID,Neighbourhood,Long,Lat,ObjectId
0,-8.816401e+06,5.434587e+06,701,GO-20141756319,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,1430,100,Assault,...,83.0,Monday,1,Assault,D42,132,Malvern (132),-79.199081,43.800281,1
1,-8.837252e+06,5.413357e+06,901,GO-20143006885,2014/09/27 00:00:00+00,2014/09/29 00:00:00+00,Other,2120,200,B&E,...,270.0,Saturday,16,Break and Enter,D52,76,Bay Street Corridor (76),-79.386383,43.662472,2
2,-8.862433e+06,5.422276e+06,702,GO-20141756802,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,2120,200,B&E,...,83.0,Monday,6,Break and Enter,D23,1,West Humber-Clairville (1),-79.612595,43.720406,3
3,-8.833104e+06,5.431887e+06,703,GO-20141760570,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Apartment,2120,200,B&E,...,83.0,Monday,15,Break and Enter,D33,47,Don Valley Village (47),-79.349121,43.782772,4
4,-8.845311e+06,5.413667e+06,902,GO-20142004859,2014/05/03 00:00:00+00,2014/05/03 00:00:00+00,Commercial,1610,210,Robbery - Business,...,123.0,Saturday,2,Robbery,D11,90,Junction Area (90),-79.458778,43.664490,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206430,-8.862292e+06,5.420779e+06,206431,GO-20192475076,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,4,Auto Theft,D23,1,West Humber-Clairville (1),-79.611320,43.710690,206431
206431,-8.856234e+06,5.405305e+06,206432,GO-20192479140,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,16,Auto Theft,D22,14,Islington-City Centre West (14),-79.556908,43.610126,206432
206432,-8.836031e+06,5.414712e+06,206433,GO-20192495839,2019/12/24 00:00:00+00,2019/12/27 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,19,Auto Theft,D51,74,North St.James Town (74),-79.375420,43.671280,206433
206433,-8.849676e+06,5.419234e+06,206434,GO-20192476502,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Other,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,0,Auto Theft,D12,30,Brookhaven-Amesbury (30),-79.497994,43.700653,206434
206434,-8.848457e+06,5.414238e+06,206435,GO-20192476230,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,House,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,8,Auto Theft,D12,111,Rockcliffe-Smythe (111),-79.487038,43.668201,206435

In [19]:

df_toronto.dropna(inplace=True,axis=0)

In [20]:
df_toronto.isnull().sum(axis=0)

X                      0
Y                      0
Index_                 0
event_unique_id        0
occurrencedate         0
reporteddate           0
premisetype            0
ucr_code               0
ucr_ext                0
type of crime          0
reportedyear           0
reportedmonth          0
reportedday            0
reporteddayofyear      0
reporteddayofweek      0
reportedhour           0
occurrenceyear         0
occurrencemonth        0
occurrenceday          0
occurrencedayofyear    0
occurrencedayofweek    0
occurrencehour         0
MCI                    0
Division               0
Hood_ID                0
Neighbourhood          0
Long                   0
Lat                    0
ObjectId               0
dtype: int64

In [21]:
df_toronto.mean

<bound method DataFrame.mean of                    X             Y  Index_ event_unique_id  \
0      -8.816401e+06  5.434587e+06     701  GO-20141756319
1      -8.837252e+06  5.413357e+06     901  GO-20143006885
2      -8.862433e+06  5.422276e+06     702  GO-20141756802
3      -8.833104e+06  5.431887e+06     703  GO-20141760570
4      -8.845311e+06  5.413667e+06     902  GO-20142004859
...              ...           ...     ...             ...
206430 -8.862292e+06  5.420779e+06  206431  GO-20192475076
206431 -8.856234e+06  5.405305e+06  206432  GO-20192479140
206432 -8.836031e+06  5.414712e+06  206433  GO-20192495839
206433 -8.849676e+06  5.419234e+06  206434  GO-20192476502
206434 -8.848457e+06  5.414238e+06  206435  GO-20192476230

                occurrencedate            reporteddate premisetype  ucr_code  \
0       2014/03/24 00:00:00+00  2014/03/24 00:00:00+00  Commercial      1430
1       2014/09/27 00:00:00+00  2014/09/29 00:00:00+00       Other      2120
2       2014/03/24 00:00:00+00  2014/03/24 00:00:00+00  Commercial      2120
3       2014/03/24 00:00:00+00  2014/03/24 00:00:00+00   Apartment      2120
4       2014/05/03 00:00:00+00  2014/05/03 00:00:00+00  Commercial      1610
...                        ...                     ...         ...       ...
206430  2019/12/24 00:00:00+00  2019/12/24 00:00:00+00     Outside      2135
206431  2019/12/24 00:00:00+00  2019/12/24 00:00:00+00     Outside      2135
206432  2019/12/24 00:00:00+00  2019/12/27 00:00:00+00     Outside      2135
206433  2019/12/24 00:00:00+00  2019/12/24 00:00:00+00       Other      2135
206434  2019/12/24 00:00:00+00  2019/12/24 00:00:00+00       House      2135

        ucr_ext           type of crime  ...  occurrencedayofyear  \
0           100                 Assault  ...                 83.0
1           200                     B&E  ...                270.0
2           200                     B&E  ...                 83.0
3           200                     B&E  ...                 83.0
4           210      Robbery - Business  ...                123.0
...         ...                     ...  ...                  ...
206430      210  Theft Of Motor Vehicle  ...                358.0
206431      210  Theft Of Motor Vehicle  ...                358.0
206432      210  Theft Of Motor Vehicle  ...                358.0
206433      210  Theft Of Motor Vehicle  ...                358.0
206434      210  Theft Of Motor Vehicle  ...                358.0

       occurrencedayofweek  occurrencehour              MCI Division  Hood_ID  \
0               Monday                   1          Assault      D42      132
1               Saturday                16  Break and Enter      D52       76
2               Monday                   6  Break and Enter      D23        1
3               Monday                  15  Break and Enter      D33       47
4               Saturday                 2          Robbery      D11       90
...                    ...             ...              ...      ...      ...
206430          Tuesday                  4       Auto Theft      D23        1
206431          Tuesday                 16       Auto Theft      D22       14
206432          Tuesday                 19       Auto Theft      D51       74
206433          Tuesday                  0       Auto Theft      D12       30
206434          Tuesday                  8       Auto Theft      D12      111

                          Neighbourhood       Long        Lat  ObjectId
0                         Malvern (132) -79.199081  43.800281         1
1              Bay Street Corridor (76) -79.386383  43.662472         2
2            West Humber-Clairville (1) -79.612595  43.720406         3
3               Don Valley Village (47) -79.349121  43.782772         4
4                    Junction Area (90) -79.458778  43.664490         5
...                                 ...        ...        ...       ...
206430       West Humber-Clairville (1) -79.611320  43.710690    206431
206431  Islington-City Centre West (14) -79.556908  43.610126    206432
206432         North St.James Town (74) -79.375420  43.671280    206433
206433         Brookhaven-Amesbury (30) -79.497994  43.700653    206434
206434          Rockcliffe-Smythe (111) -79.487038  43.668201    206435

[206376 rows x 29 columns]>

In [22]:
df_toronto.describe()

,X,Y,Index_,ucr_code,ucr_ext,reportedyear,reportedday,reporteddayofyear,reportedhour,occurrenceyear,occurrenceday,occurrencedayofyear,occurrencehour,Hood_ID,Long,Lat,ObjectId
count,2.063760e+05,2.063760e+05,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000,206376.000000
mean,-8.838205e+06,5.420273e+06,103225.154325,1696.718964,145.982978,2016.619534,15.746967,187.150173,12.838596,2016.579171,15.511024,186.506653,12.551929,72.230129,-79.394947,43.707375,103225.146112
std,1.161969e+04,8.119243e+03,59588.472658,323.491149,51.740956,1.717656,8.770544,103.599033,6.583982,1.764401,8.904154,103.884073,7.219541,40.758802,0.104381,0.052719,59588.469464
min,-8.865403e+06,5.401765e+06,1.000000,1410.000000,100.000000,2014.000000,1.000000,1.000000,0.000000,2000.000000,1.000000,1.000000,0.000000,1.000000,-79.639267,43.587093,1.000000
25%,-8.846725e+06,5.413154e+06,51623.750000,1430.000000,100.000000,2015.000000,8.000000,100.000000,8.000000,2015.000000,8.000000,99.000000,7.000000,36.000000,-79.471481,43.661152,51624.750000
50%,-8.838025e+06,5.419338e+06,103226.500000,1450.000000,100.000000,2017.000000,16.000000,189.000000,14.000000,2017.000000,16.000000,188.000000,14.000000,76.000000,-79.393333,43.701328,103226.500000
75%,-8.829811e+06,5.427154e+06,154825.250000,2120.000000,200.000000,2018.000000,23.000000,277.000000,18.000000,2018.000000,23.000000,276.000000,19.000000,108.000000,-79.319540,43.752068,154825.250000
max,-8.807943e+06,5.442380e+06,206435.000000,2135.000000,230.000000,2019.000000,31.000000,366.000000,23.000000,2019.000000,31.000000,366.000000,23.000000,140.000000,-79.123100,43.850788,206435.000000

In [24]:
df_toronto.nunique()

X                       15352
Y                       15259
Index_                 206376
event_unique_id        179765
occurrencedate           2544
reporteddate             2191
premisetype                 5
ucr_code                   21
ucr_ext                    16
type of crime              49
reportedyear                6
reportedmonth              12
reportedday                31
reporteddayofyear         366
reporteddayofweek           7
reportedhour               24
occurrenceyear             20
occurrencemonth            12
occurrenceday              31
occurrencedayofyear       366
occurrencedayofweek         7
occurrencehour             24
MCI                         5
Division                   17
Hood_ID                   140
Neighbourhood             140
Long                    15352
Lat                     15259
ObjectId               206376
dtype: int64

In [25]:
df_toronto.count()

X                      206376
Y                      206376
Index_                 206376
event_unique_id        206376
occurrencedate         206376
reporteddate           206376
premisetype            206376
ucr_code               206376
ucr_ext                206376
type of crime          206376
reportedyear           206376
reportedmonth          206376
reportedday            206376
reporteddayofyear      206376
reporteddayofweek      206376
reportedhour           206376
occurrenceyear         206376
occurrencemonth        206376
occurrenceday          206376
occurrencedayofyear    206376
occurrencedayofweek    206376
occurrencehour         206376
MCI                    206376
Division               206376
Hood_ID                206376
Neighbourhood          206376
Long                   206376
Lat                    206376
ObjectId               206376
dtype: int64

In [31]:
df_toronto['Neighbourhood'] =df_toronto['Neighbourhood'].apply(lambda x : x.split('(')[0])

In [32]:
df_toronto

,X,Y,Index_,event_unique_id,occurrencedate,reporteddate,premisetype,ucr_code,ucr_ext,type of crime,...,occurrencedayofyear,occurrencedayofweek,occurrencehour,MCI,Division,Hood_ID,Neighbourhood,Long,Lat,ObjectId
0,-8.816401e+06,5.434587e+06,701,GO-20141756319,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,1430,100,Assault,...,83.0,Monday,1,Assault,D42,132,Malvern,-79.199081,43.800281,1
1,-8.837252e+06,5.413357e+06,901,GO-20143006885,2014/09/27 00:00:00+00,2014/09/29 00:00:00+00,Other,2120,200,B&E,...,270.0,Saturday,16,Break and Enter,D52,76,Bay Street Corridor,-79.386383,43.662472,2
2,-8.862433e+06,5.422276e+06,702,GO-20141756802,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Commercial,2120,200,B&E,...,83.0,Monday,6,Break and Enter,D23,1,West Humber-Clairville,-79.612595,43.720406,3
3,-8.833104e+06,5.431887e+06,703,GO-20141760570,2014/03/24 00:00:00+00,2014/03/24 00:00:00+00,Apartment,2120,200,B&E,...,83.0,Monday,15,Break and Enter,D33,47,Don Valley Village,-79.349121,43.782772,4
4,-8.845311e+06,5.413667e+06,902,GO-20142004859,2014/05/03 00:00:00+00,2014/05/03 00:00:00+00,Commercial,1610,210,Robbery - Business,...,123.0,Saturday,2,Robbery,D11,90,Junction Area,-79.458778,43.664490,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206430,-8.862292e+06,5.420779e+06,206431,GO-20192475076,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,4,Auto Theft,D23,1,West Humber-Clairville,-79.611320,43.710690,206431
206431,-8.856234e+06,5.405305e+06,206432,GO-20192479140,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,16,Auto Theft,D22,14,Islington-City Centre West,-79.556908,43.610126,206432
206432,-8.836031e+06,5.414712e+06,206433,GO-20192495839,2019/12/24 00:00:00+00,2019/12/27 00:00:00+00,Outside,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,19,Auto Theft,D51,74,North St.James Town,-79.375420,43.671280,206433
206433,-8.849676e+06,5.419234e+06,206434,GO-20192476502,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,Other,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,0,Auto Theft,D12,30,Brookhaven-Amesbury,-79.497994,43.700653,206434
206434,-8.848457e+06,5.414238e+06,206435,GO-20192476230,2019/12/24 00:00:00+00,2019/12/24 00:00:00+00,House,2135,210,Theft Of Motor Vehicle,...,358.0,Tuesday,8,Auto Theft,D12,111,Rockcliffe-Smythe,-79.487038,43.668201,206435

In [24]:
df_toronto['occurrencedayofyear'].value_counts()

1.0      1423
305.0     881
182.0     869
152.0     817
244.0     813
         ...
63.0      442
3.0       435
4.0       419
360.0     410
366.0      97
Name: occurrencedayofyear, Length: 366, dtype: int64

In [3]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Folium installed
Libraries imported.

In [6]:
CLIENT_ID = 'HILLROI2XDCJI0CQZIFMQDAAZ3BCPHVYDECVDS010DZGAI5F' # your Foursquare ID
CLIENT_SECRET = 'LNLGG5U3QV5IWQ21GX2J0UZZXH2WD2EZUWH52A3S2KTWMUSA'

# your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: HILLROI2XDCJI0CQZIFMQDAAZ3BCPHVYDECVDS010DZGAI5F
CLIENT_SECRET:LNLGG5U3QV5IWQ21GX2J0UZZXH2WD2EZUWH52A3S2KTWMUSA

In [ ]:
long,lat =[],[]
for neigh in df_toronto['Neighbourhood']:
    geolocator = Nominatim(user_agent="foursquare_agent")
    location = geolocator.geocode(neigh+str(",Ontario"))
    if location:
        latitude = location.latitude
        longitude = location.longitude
        print(latitude, longitude)

43.8091955 -79.2217008
43.6673421 -79.3884571
43.7926732 -79.3547219
43.6654775 -79.470352
43.7689144 -79.1872905
43.6654775 -79.470352
43.6901578 -79.4749985
43.7064433 -79.4526856
43.6654775 -79.470352
43.8033965 -79.25756324844703
43.897022 -78.85919806512936
43.6694032 -79.3727041
43.6514426 -79.4510381
43.7587808 -79.5194336
43.645335 -79.5248163
45.1809266 -75.3329018
43.6534465 -79.4002002
48.437712 -89.22802176678171
43.8091955 -79.2217008
43.7587808 -79.5194336
43.7587808 -79.5194336
43.7587808 -79.5194336
43.897022 -78.85919806512936
43.6903876 -79.3832965
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.6673421 -79.3884571
43.6703377 -79.407117
43.6703377 -79.407117
43.6703377 -79.407117
43.7598243 -79.2252908
43.7572532 -79.5176975
48.437712 -89.22802176678171
43.8033965 -79.25756324844703
43.7938863 -79.42567902301055
43.6607056 -79.3604569
43.6534465 -79.4002002
43.6684402 -79.33067
43.7926732 -79.3547219
43.66269255 -79.38687480051132
43.6600648 -79.4118056
44.24463705 -76.61765730030677
43.6694032 -79.3727041
43.7437422 -79.2116324
43.724878 -79.2539688
43.71336615 -79.50450373904313
43.7067479 -79.3983271
43.787048 -79.3337137
43.704553 -79.3454074
43.645335 -79.5248163
43.6976474 -79.3011926
43.7528467 -79.282067
43.8033965 -79.25756324844703
43.6546438 -79.3697278
43.8091955 -79.2217008
43.6880189 -79.3945708
43.7689144 -79.1872905
43.616019449999996 -79.52700544999999
43.616019449999996 -79.52700544999999
43.7535196 -79.2553355
43.7184315 -79.333204
48.437712 -89.22802176678171
43.66269255 -79.38687480051132
48.437712 -89.22802176678171
43.6673421 -79.3884571
43.7572532 -79.5176975
43.6703377 -79.407117
43.8091955 -79.2217008
39.795937 -84.18226
43.897022 -78.85919806512936
43.6684402 -79.33067
43.7528467 -79.282067
43.6722234 -79.5146852
43.6971738 -79.2748232
43.7901172 -79.1733344
43.704553 -79.3454074
43.7001608 -79.5162474
43.6694032 -79.3727041
43.7926732 -79.3547219
43.6750771 -79.8225943
43.6867527 -79.4595746
43.6903876 -79.3832965
43.66269255 -79.38687480051132
43.66269255 -79.38687480051132
43.66269255 -79.38687480051132
43.897022 -78.85919806512936
43.8080383 -79.2664391
43.7394646 -79.2320997
43.7938863 -79.42567902301055
43.7394646 -79.2320997
43.897022 -78.85919806512936
43.8049304 -79.1658374
43.6007625 -79.505264
45.1809266 -75.3329018
43.7691966 -79.3766617
45.1809266 -75.3329018
43.6654704 -79.3525936
43.66269255 -79.38687480051132
43.66269255 -79.38687480051132
43.6750771 -79.8225943
43.6654775 -79.470352
43.6514426 -79.4510381
43.7938863 -79.42567902301055
39.795937 -84.18226
43.6673421 -79.3884571
43.7689144 -79.1872905
43.6901578 -79.4749985
43.7535196 -79.2553355
43.64741325 -79.43111632546047
43.6435491 -79.56532534553605
43.799003 -79.3059669
43.7926732 -79.3547219
43.66269255 -79.38687480051132
43.6654775 -79.470352
43.6654775 -79.470352
43.7064433 -79.4526856
43.7064433 -79.4526856
43.7695089 -79.354296
43.6673421 -79.3884571
43.6839242 -79.3569642
43.6839242 -79.3569642
43.6839242 -79.3569642
43.6600648 -79.4118056
43.6600648 -79.4118056
43.6673421 -79.3884571
43.6694032 -79.3727041
43.7184315 -79.333204
43.6976474 -79.3011926
43.645335 -79.5248163
43.66269255 -79.38687480051132
43.7064433 -79.4526856
43.6976474 -79.3011926
43.6867527 -79.4595746
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.6534465 -79.4002002
43.6694032 -79.3727041
43.8161778 -79.3145378
43.8161778 -79.3145378
43.64756465 -79.41388090266673
43.897022 -78.85919806512936
43.8091955 -79.2217008
43.59200455 -79.54536450659592
43.7535196 -79.2553355
43.6477917 -79.3848711
43.7142417 -79.4370715
43.897022 -78.85919806512936
43.6703377 -79.407117
43.6546438 -79.3697278
43.7598243 -79.2252908
43.6546438 -79.3697278
43.63123865 -79.58543401986114
43.7431757 -79.4517261
43.7437422 -79.2116324
43.897022 -78.85919806512936
43.6673421 -79.3884571
43.677954 -79.4430828
43.7001608 -79.5162474
44.24463705 -76.61765730030677
43.7001608 -79.5162474
43.6781015 -79.409415775
43.6673421 -79.3884571
43.6673421 -79.3884571
43.897022 -78.85919806512936
43.7078416 -79.3110743
43.6654704 -79.3525936
43.704553 -79.3454074
43.6546438 -79.3697278
43.897022 -78.85919806512936
43.6673421 -79.3884571
43.645335 -79.5248163
43.7552251 -79.1982293
43.7552251 -79.1982293
43.8091955 -79.2217008
43.8080383 -79.2664391
43.6404954 -79.4368965
43.7826012 -79.2049579
43.7826012 -79.2049579
43.7184315 -79.333204
43.6935586 -79.4139023
43.6517026 -79.4759978
44.24463705 -76.61765730030677
43.6703377 -79.407117
43.799003 -79.3059669
43.7826012 -79.2049579
43.7826012 -79.2049579
43.6654704 -79.3525936
43.6534465 -79.4002002
43.6781015 -79.409415775
43.7598243 -79.2252908
43.6880189 -79.3945708
43.8033965 -79.25756324844703
43.7689144 -79.1872905
44.24463705 -76.61765730030677
43.6655189 -79.4119373
43.7535196 -79.2553355
43.7218363 -79.2362138
43.897022 -78.85919806512936
43.7689144 -79.1872905
43.66269255 -79.38687480051132
43.6404954 -79.4368965
43.6404954 -79.4368965
43.6404954 -79.4368965
48.437712 -89.22802176678171
43.7348039 -79.3572426
43.7695089 -79.354296
43.7938863 -79.42567902301055
43.6703377 -79.407117
45.1809266 -75.3329018
43.7394646 -79.2320997
43.7348039 -79.3572426
44.24463705 -76.61765730030677
39.795937 -84.18226
43.7938863 -79.42567902301055
43.64741325 -79.43111632546047
43.8049304 -79.1658374
43.897022 -78.85919806512936
43.7437422 -79.2116324
43.7437422 -79.2116324
43.8033965 -79.25756324844703
43.6703377 -79.407117
43.6654775 -79.470352
43.6710244 -79.296712
43.66269255 -79.38687480051132
43.7437422 -79.2116324
43.6694032 -79.3727041
43.616019449999996 -79.52700544999999
43.0631891 -79.3098089
43.6007625 -79.505264
43.7572532 -79.5176975
43.897022 -78.85919806512936
43.732658 -79.3111892
43.6684402 -79.33067
48.437712 -89.22802176678171
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.897022 -78.85919806512936
43.6404954 -79.4368965
43.0631891 -79.3098089
43.7689144 -79.1872905
43.6514426 -79.4510381
43.7689144 -79.1872905
43.897022 -78.85919806512936
43.8033965 -79.25756324844703
43.6673421 -79.3884571
43.7064433 -79.4526856
43.7587808 -79.5194336
43.699971000000005 -79.33251996261595
43.7184315 -79.333204
43.699971000000005 -79.33251996261595
43.699971000000005 -79.33251996261595
43.6971738 -79.2748232
43.6971738 -79.2748232
43.7001608 -79.5162474
43.7572532 -79.5176975
43.8091955 -79.2217008
43.66269255 -79.38687480051132
43.8033965 -79.25756324844703
43.7587808 -79.5194336
43.732658 -79.3111892
43.6534465 -79.4002002
43.7598243 -79.2252908
43.8161778 -79.3145378
43.7689144 -79.1872905
43.6710244 -79.296712
43.7615095 -79.4109234
43.6536319 -79.4264389
43.64741325 -79.43111632546047
43.6007625 -79.505264
43.66269255 -79.38687480051132
43.6546438 -79.3697278
43.66269255 -79.38687480051132
43.66269255 -79.38687480051132
43.64741325 -79.43111632546047
43.6694032 -79.3727041
43.6694032 -79.3727041
43.7589503 -79.4225555
43.6781015 -79.409415775
43.7184315 -79.333204
43.7184315 -79.333204
43.6007625 -79.505264
43.6007625 -79.505264
43.6654704 -79.3525936
43.6654704 -79.3525936
43.8161778 -79.3145378
43.6404954 -79.4368965
43.7184315 -79.333204
43.7874914 -79.1507681
43.6404954 -79.4368965
43.6534465 -79.4002002
43.7535196 -79.2553355
43.7535196 -79.2553355
43.7535196 -79.2553355
43.7535196 -79.2553355
43.7203452 -79.5571025
43.6655189 -79.4119373
43.59200455 -79.54536450659592
43.897022 -78.85919806512936
43.7938863 -79.42567902301055
43.7528467 -79.282067
43.7938863 -79.42567902301055
43.64756465 -79.41388090266673
43.7184315 -79.333204

In [ ]:
import